export const posts = [
  {
    name: "Rambo",
    username: "i_love_sheep80",
    location: "Eglwysilan, Wales",
    avatar: "images/rambo-img.png",
    post: {
      url: "sheep-imgs/sheepscape-1.JPG",
      id: "sheep-1",
    },
    comment: "but how cute is that dog!?",
    likes: 21,
    id: "1",
    isLiked: false,
    uuid: `75b86329-0ddf-468f-94d4-d9177ee8d94e`,
  },
  {
    name: "Wool Ferrell",
    username: "ewe_joking",
    location: "Mexico City, Mexico",
    avatar: "images/will-img.png",
    post: {
      url: "sheep-imgs/sheepscape-2.JPG",
      id: "sheep-2",
    },
    comment: "All Mark Wahlberg does is bleat on!",
    likes: 4,
    id: "2",
    uuid: `e769a2b9-3496-47fe-8766-c3cb1a9bd33e`,
  },
  {
    name: "Obi Wool Kenobi",
    username: "baa_baa_bandit",
    location: "Stewjon, Stewjon System",
    avatar: "images/obi-img.png",
    post: {
      url: "sheep-imgs/sheepscape-3.JPG",
      id: "sheep-3",
    },
    comment: "The fleece is strong <br>with this one...",
    likes: 152,
    id: "3",
    uuid: `7e98f17b-5149-436e-807f-e76cfa5229b1`,
  },
  {
    name: "Vincent Lamb Chops",
    username: "choppy1990",
    location: "Zundert, Netherlands",
    avatar: "images/vincent-img.png",
    post: {
      url: "sheep-imgs/sheepscape-4.JPG",
      id: "sheep-4",
    },
    comment: "'Ear it is! It's all gravy, baby.",
    likes: 21,
    id: "4",
    uuid: `efe2ba6f-2795-4193-bfc3-4bd25dd07f26`,
  },
  {
    name: "Lady Baba",
    username: "the_bo_peep",
    location: "Kentucky, USA",
    avatar: "images/gaga-img.png",
    post: {
      url: "sheep-imgs/sheepscape-5.JPG",
      id: "sheep-5",
    },
    comment: "Just saw Ewe Jackman...",
    likes: 4,
    id: "5",
    uuid: `925b8c57-1e00-4f47-9338-62da4693c673`,
  },
  {
    name: "Felicity Fleece",
    username: "jd1735",
    location: "Krefeld, Germany",
    avatar: "images/felicity-img.png",
    post: {
      url: "sheep-imgs/sheepscape-6.JPG",
      id: "sheep-6",
    },
    comment:
      "Looking forward to catch up with Billy, Goat, & Gruff. Good times ahead!",
    likes: 152,
    id: "6",
    uuid: `27be9854-b910-4095-9f3a-6f3830a2d7e9`,
  },
  {
    name: "Meryl Sheep",
    username: "gus1819",
    location: "Paris, France",
    avatar: "images/streep-img.png",
    post: {
      url: "sheep-imgs/sheepscape-7.JPG",
      id: "sheep-7",
    },
    comment: "i'm feelin a bit wooly tbh",
    likes: 4,
    id: "7",
    uuid: `181a53da-9503-4d9d-972c-7cf10f16a2db`,
  },
  {
    name: "Wooly Nelson",
    username: "jd1735",
    location: "Bangkok, Thailand",
    avatar: "images/willie-img.png",
    post: {
      url: "sheep-imgs/sheepscape-8.JPG",
      id: "sheep-8",
    },
    comment: "ngl...loving dem rabbits 🐰!",
    likes: 152,
    id: "8",
    uuid: `ddf46389-4fe6-48c8-b85f-e7dc04ba058b`,
  },
];
